spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-mybatis?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@eurekaServer7002.com:7002/eureka/,http://admin:admin@eurekaServer7001.com:7001/eureka/
mybatis:
  type-aliases-package: com.example.commons.entity
  mapper-locations: mapper/*.xml