spring:
  application:
    name: eurekaServer7002
  security:
    user:
      name: user
      password: 123456
server:
  port: 7002
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaServer7001.com:7001/eureka/
  server:
    renewalPercentThreshold: 0.49