spring:
  application:
    name: eurekaServer7001.com
  security:
    user:
      name: user
      password: 123456
server:
  port: 7001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaServer7002.com:7002/eureka/
  server:
    renewalPercentThreshold: 0.49